# Site settings
title: WiFi Orchestration Tool
email: hello@cucumberwifi.io
description: > # this means to ignore newlines until "baseurl:"
  Cucumber Tony is full-stack Wi-Fi. It's the only platform you'll ever need.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cucumberwifi.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

gems: ['kramdown', 'jekyll-redirect-from']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

permalink: /community/tutorials/:title.html
